applications/departament/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departament"
urlpatterns = [
    path('list-all/', views.DepartamentListView.as_view(), name='list-all'),
    path('<int:pk>', views.DepartamentDetailView.as_view(), name='details'),
    path('new/', views.NewDepartamentView.as_view(), name='add'),
       
]

applications/employee/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

app_name = "employee"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list-all/', views.EmployeeListView.as_view(), name='list-all'),
    path('list-by-area/<shortname>', views.EmployeeListByAreaView.as_view(), name='by-area'),
    path('list-by-job/<job>', views.EmployeeListByJobView.as_view()),
    path('list-by-kword/', views.EmployeeListByKwordView.as_view()),
    path('skills/<int:id>', views.EmployeeSkillsView.as_view()),
    path('<int:id>', views.EmployeeDetailView.as_view(), name = 'details'),    
    path('add/', views.EmployeeCreateView.as_view(), name='add'),    
    path('success/', views.Success.as_view(),name='success'),    
    path('update/<int:pk>', views.EmployeeUpdateView.as_view(),name='update'),    
    path('delete/<int:pk>', views.EmployeeDeleteView.as_view(),name='delete'),    
    path('admin/', views.EmployeeAdminView.as_view(), name='admin'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('employee/', include('applications.employee.urls')),
    path('departament/', include('applications.departament.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>    
    {% block content %}
        
    {% endblock content %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
        $(document).foundation();
    </script>
</body>
</html>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text"><a href="{% url 'employee:index' %}" >EmpleadosApp</a></li>
        <li>
          <a href="#" >Empleados</a>
          <ul class="menu vertical">
            <li><a href="{% url 'employee:add' %}">Registrar Nuevo</a></li>            
            <li><a href="{% url 'employee:list-all' %}">Ver Todos</a></li>            
          </ul>
        </li>
        <li><a href="#">Departamentos</a>
          <ul class="menu vertical">
            <li><a href="{% url 'departament:add' %}">Registrar Nuevo</a></li>            
            <li><a href="{% url 'departament:list-all' %}">Ver Todos</a></li>            
          </ul>
        </li>
        <li><a href="{% url 'employee:admin' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu" style="padding: 12px;">
        <li><input type="search" placeholder="Ingrese busqueda aquí"></li>
        <li><button type="button" class="button">Buscar</button></li>
      </ul>
    </div>
  </div>
  