applications/employee/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

app_name = "employee"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list-all/', views.EmployeeListView.as_view(), name='list-all'),
    path('list-by-area/<shortname>', views.EmployeeListByAreaView.as_view(), name='by-area'),
    path('list-by-job/<job>', views.EmployeeListByJobView.as_view()),
    path('list-by-kword/', views.EmployeeListByKwordView.as_view()),
    path('skills/<int:id>', views.EmployeeSkillsView.as_view()),
    path('<int:id>', views.EmployeeDetailView.as_view(), name = 'details'),    
    path('add/', views.EmployeeCreateView.as_view(), name='add'),    
    path('success/', views.Success.as_view(),name='success'),    
    path('update/<int:pk>', views.EmployeeUpdateView.as_view(),name='update'),    
    path('delete/<int:pk>', views.EmployeeDeleteView.as_view(),name='delete'),    
    path('admin/', views.EmployeeAdminView.as_view(), name='admin'),
]

empleado/applications/employee/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "employee"
urlpatterns = [
    path('list-all/', views.EmployeeListView.as_view(), name='list-all'),
    path('list-by-area/<shortname>', views.EmployeeListByAreaView.as_view()),
    path('list-by-job/<job>', views.EmployeeListByJobView.as_view()),
    path('list-by-kword/', views.EmployeeListByKwordView.as_view()),
    path('skills/<int:id>', views.EmployeeSkillsView.as_view()),
    path('<int:id>', views.EmployeeDetailView.as_view()),    
    path('add/', views.EmployeeCreateView.as_view()),    
    path('success/', views.Success.as_view(),name='success'),    
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('employee/', include('applications.employee.urls')),
    path('departament/', include('applications.departament.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/employee/models.py
from django.db import models
from applications.departament.models import Departament
from ckeditor.fields import RichTextField

class Skill(models.Model):
    name = models.CharField('Habilidad', max_length=50)
    
    class Meta:
        ordering = ['name']        
        verbose_name = 'Habilidad Empleado'
        verbose_name_plural = 'Habilidades Empleado'
        
    def __str__(self):
        return self.name
        

class Employee(models.Model):
    
    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Desarrollador'),        
        ('4', 'Almacenista'),        
        ('5', 'Técnico'),        
        ('6', 'Enfermera'),        
        ('7', 'Otro'),        
    )
    
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre completo', max_length=120, blank=True)
    job = models.CharField('Cargo', max_length=1, choices=JOB_CHOICES)
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    # Crear relación Muchos a Muchos con 'Skill'
    skills= models.ManyToManyField(Skill, verbose_name='Habilidades')
    cv = RichTextField()
    picture = models.ImageField(upload_to='employee',blank=True,null=True)
    
    class Meta:
        ordering = ['id']        
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        
    def __str__(self):
        return str(self.id)+' '+self.first_name + ' ' + self.last_name

empleado/applications/employee/models.py
from django.db import models
from applications.departament.models import Departament
from ckeditor.fields import RichTextField

class Skill(models.Model):
    name = models.CharField('Habilidad', max_length=50)
    
    class Meta:
        ordering = ['name']        
        verbose_name = 'Habilidad Empleado'
        verbose_name_plural = 'Habilidades Empleado'
        
    def __str__(self):
        return self.name
        

class Employee(models.Model):
    
    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'DESARROLLADOR'),        
        ('4', 'ALMACENISTA'),        
        ('5', 'TÉCNICO'),        
        ('6', 'ENFERMERA'),        
        ('7', 'OTRO'),        
    )
    
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre completo', max_length=120, blank=True)
    job = models.CharField('Cargo', max_length=1, choices=JOB_CHOICES)
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    # Crear relación Muchos a Muchos con 'Skill'
    skills= models.ManyToManyField(Skill, verbose_name='Habilidades')
    cv = RichTextField()
    
    class Meta:
        ordering = ['last_name']        
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        
    def __str__(self):
        return str(self.id)+' '+self.first_name + ' ' + self.last_name

applications/employee/forms.py
from django import forms

from .models import Employee

class EmployeeForm(forms.ModelForm):
    
    class Meta:
        model = Employee
        fields = (
            'first_name',
            'last_name',
            'job',
            'departament',
            'picture',
            'skills',            
            )
        # Cambia la manera de dibujar el campo en las vistas
        widgets = {
            'skills': forms.CheckboxSelectMultiple()
        }

 

applications/employee/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView,TemplateView,UpdateView,DeleteView
from .models import Employee
from .forms import EmployeeForm


class IndexView(TemplateView):
    """Vista de pagina de Inicio"""
    template_name = "index.html"
    


class EmployeeListView(ListView):
    template_name = "employee/list-all.html"
    paginate_by = 5
    
    def get_queryset(self):
        kword = self.request.GET.get('kword','')
        queryset = Employee.objects.filter(full_name__icontains=kword)
        print (queryset)
        return queryset
    
class EmployeeListByAreaView(ListView):
    """Todos los empleados de un Area"""
    template_name = "employee/list_by_area.html"
    
   
    def get_queryset(self):
        # Recoge la variable pasada por la url
        area = self.kwargs['shortname']
        queryset = Employee.objects.filter(departament__short_name=area)
        return queryset
        
class EmployeeListByKwordView(ListView):
    """Lista empleados por palabra clave"""
    template_name = "employee/list-by-kword.html"
    context_object_name = 'employeesList'
   
    def get_queryset(self):
        kword = self.request.GET.get('kword')
        queryset = Employee.objects.filter(first_name=kword)
        print (queryset)
        return queryset
    

class EmployeeSkillsView(ListView):
    template_name = "employee/employee-skills.html"
    employee = []
    
    # Se guardan los datos de la tabla 'skill' del employee buscado
    def get_queryset(self):
        id = self.kwargs['id']
        self.employee = Employee.objects.get(id=id)
        #print(self.employee)        
        return self.employee.skills.all()
    

class EmployeeDetailView(EmployeeSkillsView):
    template_name = "employee/employee-detail.html"    
    
    #En 'context' se guarda primero los datos de queryset y luego se le agrega el nombre del employee
    def get_context_data(self, **kwargs):
        context = super(EmployeeSkillsView, self).get_context_data(**kwargs)
        context['employee'] = self.employee
        return context
    
class EmployeeListByJobView(ListView):
    """Todos los empleados de un Trabajo"""
    template_name = "employee/list-by-job.html"
    strJob = ""
    error = ""    
   
    def get_queryset(self):
        # Recoge la variable pasada por la url
        numJob = self.kwargs['job']        
        queryset = Employee.objects.filter(job=numJob)
        if (queryset.count() == 0):
            self.error = "No existen Empleados con ese Trabajo"
        else:
            #Accede al primer elemento del queryset y le asigna la cadena del valor asociada al choice del job
            self.strJob =  queryset[0].get_job_display()
        return queryset        
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega dos variables al contexto
        context["job"] = self.strJob
        context["error"] = self.error 
        return context
    
    
class EmployeeCreateView(CreateView):
    model = Employee
    template_name = "employee/add.html"
    form_class = EmployeeForm
    #success_url ='.' #Redirecciona al mismo url cuando se crea con exito
    success_url = reverse_lazy('employee:success')
    
    def form_valid(self, form):
        # copia todos los datos del form con sus campos, commit=False se utiliza para que no se guarde en la base de datos
        employee = form.save(commit=False)
        employee.full_name = employee.first_name + ' ' +employee.last_name
        employee.save()
        return super(EmployeeCreateView,self).form_valid(form)
    
class Success(TemplateView):
    template_name = "employee/success.html"


class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = "employee/update.html"
    #fields = ('__all__')
    fields = [
        'first_name',
        'last_name', 
        'job',
        'departament',
        'skills',
        'cv',
        'picture'
    ]
    success_url = reverse_lazy('employee:admin')
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Se accede a los campos a traves del request que es un diccionario
        print(request.POST['first_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        # copia todos los datos del form con sus campos, commit=False se utiliza para que no se guarde en la base de datos
        employee = form.save(commit=False)
        employee.full_name = employee.first_name + ' ' +employee.last_name
        employee.save()
        return super(EmployeeUpdateView,self).form_valid(form)

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = "employee/delete.html"
    success_url = reverse_lazy('employee:admin')

class EmployeeAdminView(EmployeeListView):
    template_name ="employee/admin.html"

empleado/applications/employee/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView,TemplateView

from .models import Employee

class EmployeeListView(ListView):
    model = Employee
    template_name = "employee/list-all.html"
    paginate_by = 5
    
class EmployeeListByAreaView(ListView):
    """Todos los empleados de un Area"""
    template_name = "employee/list-by-area.html"
    
   
    def get_queryset(self):
        # Recoge la variable pasada por la url
        area = self.kwargs['shortname']
        queryset = Employee.objects.filter(departament__short_name=area)
        return queryset
        
class EmployeeListByKwordView(ListView):
    """Lista empleados por palabra clave"""
    template_name = "employee/list-by-kword.html"
    context_object_name = 'employeesList'
   
    def get_queryset(self):
        kword = self.request.GET.get('kword')
        queryset = Employee.objects.filter(first_name=kword)
        print (queryset)
        return queryset
    

class EmployeeSkillsView(ListView):
    template_name = "employee/employee-skills.html"
    employee = []
    
    # Se guardan los datos de la tabla 'skill' del employee buscado
    def get_queryset(self):
        id = self.kwargs['id']
        self.employee = Employee.objects.get(id=id)
        #print(self.employee)        
        return self.employee.skills.all()
    

class EmployeeDetailView(EmployeeSkillsView):
    template_name = "employee/employee-detail.html"    
    
    #En 'context' se guarda primero los datos de queryset y luego se le agrega el nombre del employee
    def get_context_data(self, **kwargs):
        context = super(EmployeeSkillsView, self).get_context_data(**kwargs)
        context['employee'] = self.employee
        return context
    
class EmployeeListByJobView(ListView):
    """Todos los empleados de un Trabajo"""
    template_name = "employee/list-by-job.html"
    strJob = ""
    error = ""    
   
    def get_queryset(self):
        # Recoge la variable pasada por la url
        numJob = self.kwargs['job']        
        queryset = Employee.objects.filter(job=numJob)
        if (queryset.count() == 0):
            self.error = "No existen Empleados con ese Trabajo"
        else:
            #Accede al primer elemento del queryset y le asigna la cadena del valor asociada al choice del job
            self.strJob =  queryset[0].get_job_display()
        return queryset        
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega dos variables al contexto
        context["job"] = self.strJob
        context["error"] = self.error 
        return context
    
    
class EmployeeCreateView(CreateView):
    model = Employee
    template_name = "employee/add.html"
    #fields = ('__all__')
    fields = [
        'first_name',
        'last_name', 
        'job',
        'departament',
        'skills',
        'cv'
    ]
    #success_url ='.' #Redirecciona al mismo url cuando se crea con exito
    success_url = reverse_lazy('employee:success')
    
    def form_valid(self, form):
        # copia todos los datos del form con sus campos, commit=False se utiliza para que no se guarde en la base de datos
        employee = form.save(commit=False)
        employee.full_name = employee.first_name + ' ' +employee.last_name
        employee.save()
        return super(EmployeeCreateView,self).form_valid(form)
    
class Success(TemplateView):
    template_name = "employee/success.html"

templates/employee/add.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}
    Modificar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h1>Crear Empleado</h1>
    <div class="cell">
        <form class="grid-x  grid-padding-x" method="post" enctype="multipart/form-data">{% csrf_token %}            
            <div class="cell large-6 ">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="cell large-4 ">
                <label>Departamento:
                    {{form.departament}}
                </label>
            </div>
            <div class="cell large-4 ">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="cell large-4 ">
                <label>Habilidades:
                    {{form.skills}}
                </label>
            </div>
            <div class="cell large-12">
                <label>Curriculum Vitae:</label>
                {{form.cv}}{{form.media}}
            </div>
            <div class="cell large-4 ">
                <label>Foto:
                    {{form.picture}}
                </label>
            </div>
            <div class="cell large-12" style= "padding: 20px;">
                <button type="submit" class="success button">Guardar</button>
            </div>

        </form>
        
    </div>        
</div>
{% endblock content %}
 

templates/employee/admin.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}Lista de Todos los Empleados{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}        
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Todos los Empleados</h1>

            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Ingrese empleado a buscar...">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>

            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="300">Apellidos</th>
                        <th width="300">Departamentos</th>
                        <th colspan="2" width="150">Accion</th>
                      </tr>
                    </thead>
                    <tbody><!-- object_list retorna el contexto de la list view -->
                    {% for emp in object_list %}
                        <tr>
                            <td>{{ emp.id }}</td>
                            <td>{{ emp.first_name }}</td>
                            <td>{{ emp.last_name }}</td>
                            <td>{{ emp.departament }}</td>
                            <td><a button class="hollow button warning" href="{% url 'employee:update' emp.id %}" style="
                            margin-bottom: 0px;">Editar</button>
                            <td><a button class="hollow button alert" href="{% url 'employee:delete' emp.id %}" style="
                                    margin-bottom: 0px;">Eliminar</button>
                        </tr>                      
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell align-center primary button-group hollow no-gaps">
                <!-- Mostrar Navegacion para la paginacion, 'page_obj' es un objeto que pasa ListView automaticamente que contiene los
                atributos de la paginacion -->                   
                {% if page_obj.has_previous %}        
                    <a class="button" href="?page={{ page_obj.previous_page_number }}"><< Anterior</a>        
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if i == page_obj.number %}            
                        <a class="button" style="background-color: aqua;" href="#">{{ i }}</a>            
                    {% else %}            
                        <a class="button" href="?page={{ i }}">{{ i }}</a>            
                    {% endif %}        
                {% endfor %}
                {% if page_obj.has_next %}        
                    <a class="button" href="?page={{ page_obj.next_page_number }}">Siguiente >></a>        
                {% endif %}
                 
            </div>
        </div>
        
        
       
    </div>
{% endblock content %}
    



<body>
   
</body>
</html>

templates/employee/delete.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}
    Eliminar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado</h1>        
        <form class="cell" method="post">{% csrf_token %}
            <div class="callout secondary">
                <h5>¿Realmente deseas eliminar a <strong>{{object.full_name}}</strong>?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
            
        </form>
    </div>
</div>
    
{% endblock content %}

templates/employee/employee-detail.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}
{{employee.full_name}}
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-padding-x"> 
        <div class="cell large-12"><h2>Detalles de Empleado:</h2></div>    
        <div class="cell large-4 card" style="width: 300px;">
            <div class="card-divider">
                <h4>{{employee.full_name}}</h4>
            </div>
            {% if employee.picture %}
                <img src="{{employee.picture.url}}">
            {% else %}
                <img src="{% static 'img/empleado.jpg' %}">
            {% endif %}            
        </div>        
        <div class="callaout grid-x" style="margin-left: 15px;">
            <label class="cell large-2" style="background-color: gainsboro;"><strong>Departamento:</strong></label>
            <label class="cell large-10" style="background-color: gainsboro;">{{employee.departament}}</label>
            <label class="cell large-2"><strong>Trabajo:</strong></label>
            <label class="cell large-10">{{employee.get_job_display}}</label>
            <label class="cell large-2" style="background-color: gainsboro;"><strong> Habilidades:</strong></label>            
            <label class="cell large-10" style="background-color: gainsboro;">
                {% for sk in object_list %}
                    <li>{{ sk }}</li>
                {% endfor %}
            </label>           
            
            <label class="callout cell"><strong>Curriculum Vitae:</strong>{{employee.cv | safe}}</label>
        </div>        
        
        <div class="cell large-12" style= "padding: 20px;">
            <a href="{% url 'employee:update' employee.id %}" class="success button">Editar</a>
        </div>

    </div>
</div>
{% endblock content %}



{% comment  %}
    <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{employee.full_name}}</title>
</head>
<body>
    <h1>Datos de {{employee.first_name}} {{employee.last_name}}</h1>
    
    <!-- "get_*_display" muestra la etiqueta asociada con el valor del choice, ej. Administracion para 0 -->
    <!-- en los html las funciones se llaman sin los "()" -->
    <h4>Cargo: {{employee.get_job_display}}</h4>
    <h4>Departamento: {{employee.departament}}</h4>

    <!-- incluye al archivo "employee/employee-skills.html" para mostrar las habilidades -->
    {% include "employee/employee-skills.html" %}
</body>
</html>
{% endcomment %}

templates/employee/employee-skills.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habilidades del Empleado</title>
</head>
<body>
    <h1>Habilidades: </h1>    
    <!-- object_list retorna el contexto de la list view -->
    <ul>
        {% for sk in object_list %}
          <li>{{ sk }}</li>
        {% endfor %}
        
    </ul>    
</body>
</html>

templates/employee/list-all.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}Lista de Todos los Empleados{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}        
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Todos los Empleados</h1>

            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Ingrese empleado a buscar...">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>

            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="300">Apellidos</th>
                        <th width="300">Departamentos</th>
                        <th width="150">Accion</th>
                      </tr>
                    </thead>
                    <tbody><!-- object_list retorna el contexto de la list view -->
                    {% for emp in object_list %}
                        <tr>
                          <td>{{ emp.id }}</td>
                          <td>{{ emp.first_name }}</td>
                          <td>{{ emp.last_name }}</td>
                          <td>{{ emp.departament }}</td>
                          <td><a button class="hollow button warning" href="{% url 'employee:details' emp.id %}" style="
                            margin-bottom: 0px;">Ver</a>
                        </tr>                      
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell align-center primary button-group hollow no-gaps">
                <!-- Mostrar Navegacion para la paginacion, 'page_obj' es un objeto que pasa ListView automaticamente que contiene los
                atributos de la paginacion -->                   
                {% if page_obj.has_previous %}        
                    <a class="button" href="?page={{ page_obj.previous_page_number }}"><< Anterior</a>        
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if i == page_obj.number %}            
                        <a class="button" style="background-color: aqua;" href="#">{{ i }}</a>            
                    {% else %}            
                        <a class="button" href="?page={{ i }}">{{ i }}</a>            
                    {% endif %}        
                {% endfor %}
                {% if page_obj.has_next %}        
                    <a class="button" href="?page={{ page_obj.next_page_number }}">Siguiente >></a>        
                {% endif %}
                 
            </div>
        </div>
        
        
       
    </div>
{% endblock content %}
    



<body>
   
</body>
</html>

templates/employee/list-by-job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Empleados por Trabajo </title>
</head>
<body>
    <h1>Lista de Empleados por Trabajo: {{job}}</h1>
    <!-- object_list retorna el contexto de la list view -->
    {% if object_list %}
      <ul>        
        {% for emp in object_list %}
          <li>{{ emp }} </li>
        {% endfor %}
    </ul>
    {% else %}
        <h3>{{error}}</h3>
    {% endif %}
    
</body>
</html>

templates/employee/list-by-kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Buscar Emplados por Palabra Clave</h1>    
    <form method="GET">{% csrf_token %}
        <input type="text" name="kword" id="kword" placeholder="Ingrese Departamento aquí">
        <button type="submit">Buscar</button>
    </form>

    <h3>Lista resultado:</h3>
    <ul>
        {% for emp in employeesList %}
            <li>{{emp}}</li>
        {% endfor %}
    </ul>

</body>
</html>

templates/employee/list_by_area.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}
    Empleados del Departamento
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Empleados de este Departamento: </h1>

            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Ingrese empleado a buscar...">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>

            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="300">Apellidos</th>
                        <th width="300">Departamentos</th>
                        <th width="150">Accion</th>
                      </tr>
                    </thead>
                    <tbody><!-- object_list retorna el contexto de la list view -->
                    {% for emp in object_list %}
                        <tr>
                          <td>{{ emp.id }}</td>
                          <td>{{ emp.first_name }}</td>
                          <td>{{ emp.last_name }}</td>
                          <td>{{ emp.departament }}</td>
                          <td><a button class="hollow button warning" href="{% url 'employee:details' emp.id %}" style="
                            margin-bottom: 0px;">Ver</button>
                        </tr>                      
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell align-center primary button-group hollow no-gaps">
                <!-- Mostrar Navegacion para la paginacion, 'page_obj' es un objeto que pasa ListView automaticamente que contiene los
                atributos de la paginacion -->                   
                {% if page_obj.has_previous %}        
                    <a class="button" href="?page={{ page_obj.previous_page_number }}"><< Anterior</a>        
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if i == page_obj.number %}            
                        <a class="button" style="background-color: aqua;" href="#">{{ i }}</a>            
                    {% else %}            
                        <a class="button" href="?page={{ i }}">{{ i }}</a>            
                    {% endif %}        
                {% endfor %}
                {% if page_obj.has_next %}        
                    <a class="button" href="?page={{ page_obj.next_page_number }}">Siguiente >></a>        
                {% endif %}
                 
            </div>
        </div>

    </div>
{% endblock content %}
    

templates/employee/success.html
<h1>Registrado Satisfactoriamente</h1>