applications/departament/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departament"
urlpatterns = [
    path('list-all/', views.DepartamentListView.as_view(), name='list-all'),
    path('<int:pk>', views.DepartamentDetailView.as_view(), name='details'),
    path('new/', views.NewDepartamentView.as_view(), name='add'),
       
]

applications/employee/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

app_name = "employee"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list-all/', views.EmployeeListView.as_view(), name='list-all'),
    path('list-by-area/<shortname>', views.EmployeeListByAreaView.as_view(), name='by-area'),
    path('list-by-job/<job>', views.EmployeeListByJobView.as_view()),
    path('list-by-kword/', views.EmployeeListByKwordView.as_view()),
    path('skills/<int:id>', views.EmployeeSkillsView.as_view()),
    path('<int:id>', views.EmployeeDetailView.as_view(), name = 'details'),    
    path('add/', views.EmployeeCreateView.as_view(), name='add'),    
    path('success/', views.Success.as_view(),name='success'),    
    path('update/<int:pk>', views.EmployeeUpdateView.as_view(),name='update'),    
    path('delete/<int:pk>', views.EmployeeDeleteView.as_view(),name='delete'),    
    path('admin/', views.EmployeeAdminView.as_view(), name='admin'),
]

empleado/applications/departament/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departament"
urlpatterns = [
    path('list-all/', views.DepartamentListView.as_view(), name='list-all'),
    path('<int:pk>', views.DepartamentDetailView.as_view(), name='details'),
       
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('employee/', include('applications.employee.urls')),
    path('departament/', include('applications.departament.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departament/models.py
from django.db import models

class Departament(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado',default=False)
    
    class Meta:
        ordering = ['name']
        managed = True
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        unique_together = ('name','short_name')
    
    def __str__(self):
        return self.short_name

empleado/applications/departament/models.py
from django.db import models

class Departament(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado',default=False)
    
    class Meta:
        ordering = ['name']
        managed = True
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        unique_together = ('name','short_name')
    
    def __str__(self):
        return self.short_name

applications/departament/forms.py
from django import forms

class NewDepartamentForm(forms.Form):
    first_name = forms.CharField( max_length=50)
    last_name = forms.CharField( max_length=50)
    departament = forms.CharField( max_length=50)
    short_name = forms.CharField( max_length=20)

applications/departament/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from .forms import NewDepartamentForm
from .models import Departament
from applications.employee.models import Employee
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView

class DepartamentListView(ListView):
    template_name = "departament/list-all.html"
    paginate_by = 5
    
    def get_queryset(self):
        kword = self.request.GET.get('kword','')
        queryset = Departament.objects.filter(name__icontains=kword)
        print (queryset)
        return queryset
    
class DepartamentDetailView(DetailView):
    model = Departament
    template_name = "departament/details.html"

class NewDepartamentView(FormView):
    template_name = 'departament/new_departament.html'
    form_class = NewDepartamentForm
    success_url = reverse_lazy('employee:success')
    
    def form_valid(self, form):
        departament = form.cleaned_data['departament']
        short_name = form.cleaned_data['short_name']
        depa = Departament.objects.create(
            name = departament,
            short_name = short_name,            
        )
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        Employee.objects.create(
            first_name = first_name,
            last_name = last_name,
            job = '1',
            departament = depa,
        )
        
        return super(NewDepartamentView,self).form_valid(form)
    

empleado/applications/departament/views.py
from django.shortcuts import render
from .models import Departament
from django.views.generic import ListView, DetailView

class DepartamentListView(ListView):
    template_name = "departament/list-all.html"
    
    def get_queryset(self):
        return Departament.objects.all()
    
class DepartamentDetailView(DetailView):
    model = Departament
    template_name = "departament/details.html"

    

templates/departament/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles de Departamento {{departament.short_name}}</title>
</head>
<body>
    <h1>Departamento: {{departament.short_name}}</h1>
    <h3>Nombre Completo: </h3>{{departament.name}}
</body>
</html>

templates/departament/list-all.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}Lista de Todos los Departamentos{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}    
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Todos los Departamentos</h1>

            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Ingrese departamento a buscar...">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>

            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombre</th>
                        <th width="300">Alias</th>                        
                        <th width="150">Accion</th>
                      </tr>
                    </thead>
                    <tbody><!-- object_list retorna el contexto de la list view -->
                    {% for dep in object_list %}
                        <tr>
                          <td>{{ dep.id }}</td>
                          <td>{{ dep.name }}</td>
                          <td>{{ dep.short_name }}</td>
                          <td><a button class="hollow button warning" href="{% url 'employee:by-area' dep.short_name %}" style="
                            margin-bottom: 0px;">Ver Empleados</button>
                        </tr>                      
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell align-center primary button-group hollow no-gaps">
                <!-- Mostrar Navegacion para la paginacion, 'page_obj' es un objeto que pasa ListView automaticamente que contiene los
                atributos de la paginacion -->                   
                {% if page_obj.has_previous %}        
                    <a class="button" href="?page={{ page_obj.previous_page_number }}"><< Anterior</a>        
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if i == page_obj.number %}            
                        <a class="button" style="background-color: aqua;" href="#">{{ i }}</a>            
                    {% else %}            
                        <a class="button" href="?page={{ i }}">{{ i }}</a>            
                    {% endif %}        
                {% endfor %}
                {% if page_obj.has_next %}        
                    <a class="button" href="?page={{ page_obj.next_page_number }}">Siguiente >></a>        
                {% endif %}
                 
            </div>
        </div>
        
        
       
    </div>
{% endblock content %}

templates/departament/new_departament.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}
    Crear Departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h1>Registrar Departamento</h1>
    <div class="cell">
        <form class="grid-x callout grid-padding-x" method="post" enctype="multipart/form-data">{% csrf_token %}  
            <h4 class="cell">Datos del Encargado:</h4>          
            <div class="cell large-6 ">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <h4 class="cell">Datos del Departamento:</h4>          
            <div class="cell large-6 ">
                <label>Departamento:
                    {{form.departament}}
                </label>
            </div>
            <div class="cell large-6 ">
                <label>Nombre Corto:
                    {{form.short_name}}
                </label>
            </div>
            
            <div class="cell large-12" style= "padding: 20px;">
                <button type="submit" class="success button">Guardar</button>
            </div>

        </form>
        
    </div>        
</div>

{% endblock content %}